export const coreProps = {
    modelValue: { type: Boolean, default: true },
    startDate: { type: String, default: '' },
    endDate: { type: String, default: '' },
    persianMode: { type: Boolean, default: true },
    buttonSelectClass: { type: String, default: '' },
    selectYearClass: { type: String, default: '' },
    activeYearClass: { type: String, default: '' },
    onActiveYearClass: { type: String, default: '' },
    selectMonthClass: { type: String, default: '' },
    activeMonthClass: { type: String, default: '' },
    onActiveMonthClass: { type: String, default: '' },
    calenderClass: { type: String, default: '' },
    dayOfWeekClass: { type: String, default: '' },
    separatorClass: { type: String, default: '' },
    activeDayClass: { type: String, default: '' },
    nowDayClass: { type: String, default: '' },
    onActiveDayClass: { type: String, default: '' },
}