export const datePickerClasses = {
    buttonClasses: "inline",
    buttonSelect: "mr-4 bg-gray-600",
    selectYear: "grid grid-cols-3 gap-4 w-[430px] h-[400px] max-w-[430px] mt-3 border rounded-md p-5 text-center overflow-y-scroll",
    activeYear: "flex justify-center items-center w-full h-10 select-none bg-gray-300 rounded-lg shadow hover:bg-gray-200 cursor-pointer",
    onActiveYear: "flex justify-center items-center w-full h-10 select-none bg-gray-100 rounded-lg shadow hover:bg-gray-200 cursor-pointer",
    selectMonth: "grid grid-cols-3 gap-4 w-[430px] h-[400px] max-w-[430px] mt-3 border rounded-md p-5 text-center",
    activeMonth: "flex justify-center items-center w-30 h-16 select-none bg-gray-300 rounded-lg shadow hover:bg-gray-400 cursor-pointer",
    onActiveMonth: "flex justify-center items-center w-30 h-16 select-none bg-gray-100 rounded-lg shadow hover:bg-gray-200 cursor-pointer",
    calender: "grid grid-cols-7 w-[430px] h-[400px] gap-4 max-w-[430px] mt-3 border rounded-md evaluation-4 p-2",
    dayOfWeek: "font-bold text-center flex justify-center items-center w-10 h-10 select-none",
    separator: "w-10 h-10 bg-transparent text-center flex justify-center items-center",
    activeDay: "w-10 h-10 text-center flex justify-center items-center rounded-full select-none cursor-pointer bg-gray-200",
    nowDay: "border border-black",
    onActiveDay: "w-10 h-10 bg-transparent text-center flex justify-center items-center rounded-full select-none cursor-pointer hover:bg-gray-100",
}