export const dateRangeClasses = {
    buttonClasses: "inline",
    buttonSelect: "mr-4 bg-slate-700",
    selectYear: "grid grid-cols-3 gap-4 w-[430px] h-[400px] max-w-[430px] mt-3 border rounded-md p-5 text-center overflow-y-scroll",
    activeYear: "flex justify-center items-center w-full h-10 select-none bg-slate-700 text-white rounded-lg shadow hover:bg-slate-600 transition duration-300 cursor-pointer",
    onActiveYear: "flex justify-center items-center w-full h-10 select-none bg-slate-200 rounded-lg shadow hover:bg-slate-300 transition duration-300 cursor-pointer",
    selectMonth: "grid grid-cols-3 gap-4 w-[430px] h-[400px] max-w-[430px] mt-3 border rounded-md p-5 text-center",
    activeMonth: "flex justify-center items-center w-30 h-16 select-none bg-slate-700 text-white rounded-lg shadow hover:bg-slate-600 transition duration-300 cursor-pointer",
    onActiveMonth: "flex justify-center items-center w-30 h-16 select-none bg-slate-200 rounded-lg shadow hover:bg-slate-300 transition duration-300 cursor-pointer",
    calender: "grid grid-cols-7 w-[430px] h-[400px] gap-4 max-w-[430px] mt-3 border rounded-md evaluation-4 p-2 bg-slate-200",
    dayOfWeek: "font-bold text-center flex justify-center items-center w-10 h-10 select-none",
    separator: "w-10 h-10 bg-transparent text-center flex justify-center items-center",
    activeDay: "w-10 h-10 text-center flex justify-center items-center rounded-full select-none cursor-pointer bg-slate-700 text-white",
    nowDay: "border border-black",
    onActiveDay: "w-10 h-10 bg-transparent text-center flex justify-center items-center rounded-full select-none cursor-pointer hover:bg-slate-300 transition duration-300",
}